export { useWorkspace } from './useWorkspace';
export { projectName, groupProjects, selectSession, selectProject, prepareConversation, addSession, removeSession } from './selection';
export type { WorkspaceSession, SessionWorkspace } from './selection';
export { useSessionInput } from './useSessionInput';
export { ProjectNav, ProjectNavigation, type ProjectNavItem, type ProjectNavLabels, type ProjectNavProps } from './ProjectNav';
export { ProjectSidebar } from './ProjectSidebar';
export { WorkspaceChrome, type WorkspaceChromeProps } from './WorkspaceChrome';
export { EnvironmentPopover } from './EnvironmentPopover';
export { useSidePanelTabs, type SidePanelKind } from './useSidePanelTabs';
export { HistorySearchDialog } from './HistorySearchDialog';
export { TaskToolbar, type TaskToolbarProps } from './TaskToolbar';
export { TaskDetailsPanel, type TaskDetailsPanelProps } from './TaskDetailsPanel';
export { readWorkspaceView, writeWorkspaceView, type WorkspaceViewPersistence } from './workspace-view-persistence';
export { SessionTabs, type WorkspaceSessionTab, type SessionTabsLabels, type SessionTabsProps } from './SessionTabs';
export { referencePaths } from './reference-paths';
export { SidePanelHost } from './SidePanelHost';
