import { StrictMode, useState, type ReactNode } from 'react';
import { createRoot } from 'react-dom/client';
import { UIProvider, Checkbox, Radio, Slider, Button, IconButton, Icon, TextField, Select, DropdownMenu, Tooltip, Tag, StatusBadge, Tabs, Dialog, Collapsible, InlineRename, ResizableWorkspace, MotionSample, Breadcrumbs, type MotionMode, type RunStatus } from '../../src/renderer/ui';
import { ToolExecutionCard, ChatMessage } from '../../src/renderer/features/conversation';
import { ProjectNav, SessionTabs } from '../../src/renderer/features/workspace';
import { InspectorHeader, FileRow } from '../../src/renderer/features/change-review';
import { ComposerPreview, NotificationsPreview, DialogExamples, ChatExamples } from './CompletionExamples';
import * as fixtures from './fixtures';
import { DocumentExamples } from './DocumentExamples';
import '../../src/renderer/ui/tokens.css';
import '../../src/renderer/ui/tailwind.css';
import '../../src/renderer/ui/ui.css';
import '../../src/renderer/features/workspace/workspace-navigation.css';
import '../../src/renderer/features/change-review/change-review.css';
import '../../src/renderer/features/conversation/conversation.css';
import './preview.css';
const sections = [{ value: 'foundations', label: 'Foundations' }, { value: 'primitives', label: '通用组件' }, { value: 'modules', label: '模块组件' }, { value: 'composition', label: '组合交互' }];
function Card({ title, note, children, wide = false }: { title: string; note?: string; children: ReactNode; wide?: boolean }) {
  return <section className={`preview-card ${wide ? 'preview-wide' : ''}`}><div className="preview-card-heading"><h3>{title}</h3>{note && <span className="ui-meta">{note}</span>}</div>{children}</section>;
}
function Workbench() {
  const [theme, setTheme] = useState<'light' | 'dark'>('light'), [motion, setMotion] = useState<MotionMode>('normal'), [section, setSection] = useState('primitives');
  const [state, setState] = useState('default'), [choice, setChoice] = useState('balanced'), [dialog, setDialog] = useState(false), [tab, setTab] = useState('overview'), [replay, setReplay] = useState(0);
  const [name, setName] = useState('Explore component ideas'), [failRename, setFailRename] = useState(false), [notice, setNotice] = useState('');
  const [project, setProject] = useState(fixtures.projects[0].cwd), [sessions, setSessions] = useState(fixtures.sessions), [session, setSession] = useState('plan'), [status, setStatus] = useState<RunStatus>('success');
  async function rename(value: string, id?: string) {
    await new Promise(resolve => setTimeout(resolve, 750));
    if (failRename) throw new Error('Demo rejection — draft preserved. Disable failure and retry.');
    if (id) setSessions(previous => previous.map(item => item.id === id ? { ...item, title: value } : item)); else setName(value);
  }
  const projectNav = <ProjectNav labels={{ title: '项目', add: '添加项目', empty: '暂无项目' }} projects={fixtures.projects} selectedCwd={project} onSelect={setProject} onAdd={() => setNotice('Add project callback · preview only')}/>;
  const sessionTabs = <SessionTabs showOverflow labels={{ title: '会话', add: '新建会话', rename: { hint: '双击或 F2 重命名', input: name => `重命名 ${name}`, save: '保存', cancel: '取消', empty: '名称不能为空', failed: '重命名失败，请重试' } }} sessions={sessions} activeId={session} onSelect={setSession} onRename={(id, value) => rename(value, id)} onAdd={() => { const id = `demo-${sessions.length}`; setSessions([...sessions, { id, title: '未命名探索' }]); setSession(id); }}/>;
  const tool = <ToolExecutionCard labels={{ details: '执行详情', statuses: { idle: '空闲', running: '运行中', success: '已完成', error: '失败', paused: '暂停' } }} title="已读取文件运行了命令" icon={<Icon name="file"/>} status={status}><pre>3 feature components inspected{'\n'}Preview fixture only.{'\n'}No desktop bridge invoked.</pre></ToolExecutionCard>;
  const inspector = <><InspectorHeader title="检查器" labels={{ refresh: '刷新检查' }} count={3} onRefresh={() => setNotice('Refresh callback · preview only')}/><div className="preview-inspector-group"><span className="ui-meta">组件文件</span><FileRow labels={{ open: '查看 Button.tsx' }} name="Button.tsx" detail="UI" onOpen={() => setNotice('File callback · Button.tsx')}/><FileRow labels={{ open: '查看 motion.tsx' }} name="motion.tsx" detail="UI" onOpen={() => setNotice('File callback · motion.tsx')}/><FileRow labels={{ open: '查看 ProjectNav' }} name="ProjectNav" detail="Feature" onOpen={() => setNotice('File callback · ProjectNav')}/></div><div className="preview-inspector-group"><span className="ui-meta">检查状态</span><p>等待进一步检查。</p><span className="ui-meta">仅本地预览 · 待视觉确认</span></div></>;
  return <UIProvider theme={theme} motion={motion}><div className="preview-shell">
    <header className="preview-header"><div className="preview-wordmark"><Icon name="pi"/><strong>PUA</strong><span>组件工作台</span><Tag>TEST ONLY</Tag></div><div className="preview-controls"><Select label="Theme" value={theme} options={[{ value: 'light', label: 'Light' }, { value: 'dark', label: 'Dark' }]} onChange={value => setTheme(value as 'light' | 'dark')}/><Select label="Motion" value={motion} options={[{ value: 'normal', label: 'Motion · normal' }, { value: 'slow', label: 'Motion · 3× slower' }, { value: 'off', label: 'Motion · off' }]} onChange={value => setMotion(value as MotionMode)}/></div></header>
    <div className="preview-nav"><Tabs label="Workbench sections" items={sections} value={section} onChange={setSection}/><span className="ui-meta">Fixture data only · no Pi / Git / disk · no desktop bridge</span></div>
    {section === 'foundations' && <div className="preview-grid">
      <Card title="Semantic surfaces" note="codex-theme-v1 · Catppuccin" wide><div className="preview-swatches">{['canvas', 'surface', 'muted', 'selected', 'accent', 'border', 'text', 'diff-added', 'diff-removed', 'skill', 'link', 'highlight-bg'].map(token => <div key={token}><span style={{ background: `var(--ui-${token})` }}/><strong>{token}</strong></div>)}</div></Card>
      <Card title="Typography roles" note={theme === 'light' ? 'Geist / Inter · Geist Mono · 本机回退' : '默认系统字体 · 导出值 null'}><div className="preview-type-roles"><p className="preview-type-reading">阅读正文 · 15 / 24.75 / 400<br/>为长回答留出节奏，而不是把文字塞进一屏。</p><h2>章节 · 16 / 24 / 600</h2><p>导航与控件 · 13 / 20 / 400，当前项 500</p><span className="ui-meta">元信息 · 12 / 18 / 400 · 0.8s · 3 个文件</span><a href="#typography-roles">链接 · 单独语义与下划线</a></div></Card>
      <Card title="Rhythm & shape" note="PUA layout · exported theme colors"><div className="preview-spacing">{[4, 6, 8, 12, 16, 24].map(size => <div key={size}><span style={{ width: size, height: size }}/><small>{size}</small></div>)}</div><p>Controls 28px / radius 8px · overlays 12px · composer 20px</p><p className="ui-meta">明暗基础色与字体栈来自主题导出；尺寸、派生色和代码片段配色为本地实现。</p></Card>
      <Card title="Motion tokens" note="GSAP 3.15.0 · @gsap/react 2.1.2"><MotionSample replay={replay}/><div className="preview-row"><details className="preview-test-controls"><summary>测试控制 · 重播</summary><Button onClick={() => setReplay(replay + 1)}>Replay transition</Button></details><span className="ui-meta">Overlay 0.16s · structure 0.24s</span></div><p className="ui-meta">power2.out · system reduced-motion takes priority. Hover is CSS; structural motion is GSAP.</p></Card>
      <Card title="Semantic status" note="Color + icon + label"><div className="preview-row">{(['idle', 'running', 'success', 'paused', 'error'] as const).map(value => <StatusBadge key={value} status={value}/>)}</div><div className="preview-row"><Tag>Interface</Tag><Tag>Design system</Tag></div></Card>
      <Card title="图标语义" note="Lucide · 16px · 1.75 stroke" wide><div className="preview-icon-catalog">{(['folder', 'file', 'search', 'plus', 'chat', 'panel', 'copy', 'link', 'refresh', 'settings', 'terminal', 'clock', 'running', 'success', 'warning', 'error', 'pause', 'up'] as const).map(name => <span key={name}><Icon name={name}/><span>{name}</span></span>)}</div></Card>
      <Card title="文档与语义颜色" note="链接 / 高亮 / 状态 / 代码 / 变更" wide><ChatMessage role="assistant" author="小派"><DocumentExamples/></ChatMessage></Card>
    </div>}
    {section === 'primitives' && <><div className="preview-section-toolbar"><span><strong>Primitives</strong><span className="ui-meta"> / consistent states, real interactions</span></span><Select label="Component state" value={state} onChange={setState} options={['default', 'disabled', 'busy', 'error'].map(value => ({ value, label: `State · ${value}` }))}/></div><div className="preview-grid">
      <Card title="Actions" note="Button / IconButton"><div className="preview-row"><Button variant="primary" disabled={state === 'disabled'} busy={state === 'busy'} onClick={() => setNotice('Primary action callback')}>Create project<Icon name="plus"/></Button><Button disabled={state === 'disabled'} onClick={() => setNotice('Secondary action callback')}>Secondary</Button><Button variant="ghost" onClick={() => setNotice('Ghost action callback')}>Quiet action</Button><IconButton label="Search components" icon="search" disabled={state === 'disabled'} onClick={() => setNotice('Search callback')}/></div><div className="preview-row"><Button variant="danger" onClick={() => setDialog(true)}>Delete item</Button><Button disabled>Unavailable</Button><Button busy>Saving</Button></div><p className="ui-meta">Hover, hold to press, then Tab: selected fill and keyboard focus are different states.</p></Card>
      <Card title="Inputs & choices" note="TextField / Select / DropdownMenu"><TextField label="Project name" placeholder="A place for your next idea" disabled={state === 'disabled' || state === 'busy'} error={state === 'error' ? 'A project name is required.' : undefined}/><div className="preview-row"><Select label="Detail level" value={choice} options={[{ value: 'brief', label: 'Brief' }, { value: 'balanced', label: 'Balanced' }, { value: 'detailed', label: 'Detailed' }, { value: 'unavailable', label: 'Unavailable', disabled: true }]} onChange={setChoice} disabled={state === 'disabled'}/><DropdownMenu label="More actions" items={[{ value: 'duplicate', label: 'Duplicate' }, { value: 'archive', label: 'Archive' }]} onAction={value => setNotice(`${value} callback`)}/><Tooltip content="Tooltips also open with keyboard focus."><IconButton label="Explain choices" icon="chat" variant="ghost"/></Tooltip></div></Card>
      <Card title="Form controls" note="Checkbox / Radio / Slider"><div className="preview-row"><label><Checkbox defaultChecked aria-label="自动重试"/> 自动重试</label><label><Radio name="preview-mode" defaultChecked/> 新会话</label><label><Radio name="preview-mode"/> 继续会话</label><label>字号<Slider aria-label="预览字号" min={10} max={28} defaultValue={14}/></label><Checkbox aria-label="禁用选项" disabled/></div></Card>
      <Card title="Navigation & labels" note="Tabs / Tag / StatusBadge"><Tabs label="Sample views" items={[{ value: 'overview', label: 'Overview' }, { value: 'activity', label: 'Activity' }, { value: 'files', label: 'Files' }]} value={tab} onChange={setTab}/><div role="tabpanel" aria-label={tab} className="preview-row"><Tag>{tab}</Tag><StatusBadge status="success"/><StatusBadge status="running"/><StatusBadge status="error"/></div><p className="ui-meta">Arrow keys move tabs. Menus: arrows, Home/End, Enter, Escape; Tab leaves.</p></Card>
      <Card title="Inline rename" note="Double-click / F2"><InlineRename value={name} onRename={value => rename(value)}/><div className="preview-row"><details className="preview-test-controls"><summary>测试控制 · 改名</summary><Button variant={failRename ? 'primary' : 'secondary'} aria-pressed={failRename} onClick={() => setFailRename(!failRename)}>Simulate async failure: {failRename ? 'on' : 'off'}</Button></details></div><p className="ui-meta">750ms save · Enter commits · Escape cancels · blur retains draft · IME safe.</p></Card>
      <div className="preview-column"><Card title="Disclosure & dialog" note="Inert when closed"><Collapsible title="Explore the interaction rules"><p>Content enters with a subtle shift and fade. Closed content leaves the focus order immediately.</p><Button onClick={() => setDialog(true)}>Open review dialog</Button></Collapsible><div className="preview-row"><Button onClick={() => setDialog(true)}>Open dialog</Button></div><DialogExamples/></Card>
      <Card title="Motion study" note="Replay / interrupt / reduce"><MotionSample replay={replay}/><div className="preview-row"><details className="preview-test-controls"><summary>测试控制 · 重播</summary><Button onClick={() => setReplay(replay + 1)}>Replay transition</Button></details><span className="ui-meta">0.24s · power2.out</span></div></Card></div>
      <Card title="通知与导航" note="Message / ToastHost / Breadcrumbs"><NotificationsPreview/></Card>
    </div></>}
    {section === 'modules' && <><div className="preview-section-toolbar"><strong>Project-level modules</strong><Select label="Execution status" value={status} onChange={value => setStatus(value as RunStatus)} options={['idle', 'running', 'success', 'paused', 'error'].map(value => ({ value, label: value }))}/></div><div className="preview-grid"><Card title="ProjectNav" note="cwd identity · name-first">{projectNav}</Card><Card title="InspectorHeader / FileRow" note="Composable callbacks">{inspector}</Card><Card title="SessionTabs" note="Double-click / F2 · 750ms async rename">{sessionTabs}<div className="preview-row"><details className="preview-test-controls"><summary>测试控制 · 改名</summary><Button aria-pressed={failRename} onClick={() => setFailRename(!failRename)}>Rename failure: {failRename ? 'on' : 'off'}</Button></details></div></Card><Card title="ToolExecutionCard" note="Status + progressive detail">{tool}</Card><Card title="ChatMessage" note="安全文本 / 元信息 / 流式 / 错误 / 操作"><ChatExamples/></Card><Card title="Composer" note="受控草稿 / 附件 / 队列 / 停止 · 仅示例适配器"><ComposerPreview conversationKey="module-demo"/></Card></div></>}
    {section === 'composition' && <><div className="preview-section-toolbar"><span className="ui-meta">本地对话示例 · 阅读与交互</span><details className="preview-test-controls"><summary>测试控制 · 改名</summary><Button aria-pressed={failRename} onClick={() => setFailRename(!failRename)}>Rename failure: {failRename ? 'on' : 'off'}</Button></details></div><ResizableWorkspace motionControls left={projectNav} right={inspector}><div className="preview-conversation">{sessionTabs}<div className="preview-conversation-location"><Breadcrumbs label="会话位置" items={[{ id: 'project', label: 'Atlas', onSelect: () => setNotice('项目导航 · 仅本地示例') }, { id: 'session', label: sessions.find(item => item.id === session)?.title ?? '未命名探索' }]}/></div><ComposerPreview conversationKey={session}>
      <ChatMessage role="user" author="你" labels={{ user: '用户' }}>切换会话时，怎样保留草稿，又避免旧请求覆盖新输入？</ChatMessage>
      <ChatMessage role="assistant" author="小派" labels={{ assistant: '助手' }}><p>将草稿保存在调用方，以会话标识区分。发送时捕获当前快照，完成后再检查它是否仍是那份草稿；不要在异步回调里直接清空当前输入框。</p></ChatMessage>
      <ChatMessage role="user" author="你" labels={{ user: '用户' }}>请给出实施步骤和检查方法，先不接入真实模型。</ChatMessage>
      {tool}
      <ToolExecutionCard title="已使用项目集成" status="success" icon={<Icon name="link" style={{ color: 'var(--ui-skill)' }}/>} labels={{ details: '集成详情', statuses: { success: '已完成' } }}><p>读取了本地示例中的项目说明与任务列表。此处没有连接真实集成。</p></ToolExecutionCard>
      <ChatMessage role="assistant" author="小派" metadata="本地示例 · 用时 0.8s" labels={{ assistant: '助手' }}>
        <p>可以把这次调整限制在受控草稿和提交回写上。界面负责展示状态，调用方负责决定哪一份数据可以更新。</p>
        <h2>实施步骤</h2><ol><li><strong>按会话保存草稿。</strong>使用稳定的 <code>conversationKey</code> 索引正文和附件。切换标签只改变当前查看的会话，不销毁其他草稿。</li><li><strong>提交时捕获快照。</strong>把会话标识、正文和附件一起交给回调。请求等待期间仍可输入下一条内容。</li><li><strong>有条件地清理。</strong>成功后确认会话和草稿版本都匹配；如果用户已经编辑，保留新内容。失败则展示错误，留下原正文与附件。</li></ol>
        <h2>回写示例</h2><p>下面是本地 Adapter 的核心判断，不是生产持久化或请求取消实现：</p><pre tabIndex={0} aria-label="回写示例代码"><code>{`const submitted = entry.draft;
await send(snapshot);

setEntries(previous => {
  const entry = previous[snapshot.conversationKey];
  return updateEntry(previous, snapshot.conversationKey, {
    ...entry,
    draft: entry.draft === submitted ? emptyDraft : entry.draft,
  });
});`}</code></pre>
        <h2>检查方法</h2><ul><li>在会话 A 发起请求后切换到 B，输入“下一轮计划 2026”。A 完成时，B 的草稿和附件应保持不变。</li><li>等待请求时继续修改 A 的正文，成功回写不应清空新内容。</li><li>模拟失败后检查错误、正文、附件与重试操作；停止运行也不应清空后续草稿。</li></ul>
        <blockquote><p>紧凑操作不等于紧缩阅读。失败原因和下一步操作应完整可读，不能为了放进一屏而裁掉。</p></blockquote>
        <DocumentExamples/>
        <h2>非目标</h2><p>本例不接入 Pi、IPC、真实文件选择或磁盘，不新增业务 store，也不修改生产 App。真实请求的取消和版本校验仍需要调用方在接入时落实。</p>
        <h2>检查结果</h2><table tabIndex={0} aria-label="本地检查结果"><thead><tr><th>场景</th><th>本地示例预期</th></tr></thead><tbody><tr><td>切换会话</td><td>各自草稿保留</td></tr><tr><td>请求中编辑</td><td>新输入不覆盖</td></tr><tr><td>发送失败</td><td>错误可读，允许重试</td></tr></tbody></table><p data-reading-end>以上是验证步骤，而非真实服务通过证明。可继续在下方输入，或<a href="#local-checks" onClick={event => { event.preventDefault(); setNotice('检查清单已定位 · 仅本地回调'); }}>查看本地检查清单</a>。</p>
      </ChatMessage>
    </ComposerPreview></div></ResizableWorkspace></>}
    <div className="preview-notice" role="status">{notice || 'Explore freely. All changes stay in this preview.'}</div>
    <Dialog open={dialog} title="Review this direction" onClose={() => setDialog(false)}><p>This is a component proposal. Closing this dialog does not approve or replace the production App.</p><div className="preview-row"><Tooltip content="关闭此本地预览对话框，返回组件工作台；此操作不会批准或替换正式 App。"><Button variant="primary" onClick={() => setDialog(false)}>Back to components</Button></Tooltip><Button onClick={() => setDialog(false)}>Cancel</Button></div></Dialog>
  </div></UIProvider>;
}
createRoot(document.getElementById('component-preview')!).render(<StrictMode><Workbench/></StrictMode>);
