import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { checkBoundaries, checkSource } from '../scripts/check-boundaries';

const root = process.cwd();
describe('TypeScript import/channel gate', () => {
  it('checks the actual production tree', () => {
    expect(checkBoundaries(root)).toEqual([]);
  });
  it.each([
    ...['react', 'node:fs', '@mariozechner/pi-ai', '../../../shared/ipc/desktop-api', '../../../platform/filesystem/expand-home', './useWorkspace', './index'].flatMap(target =>
      [`import '${target}'`, `export * from '${target}'`, `import type { Value } from '${target}'`, `type Value = import('${target}').Value`, `require('${target}')`, `import('${target}')`, `import value = require('${target}')`].map(source => ['src/renderer/features/workspace/selection.ts', source])),
    ...['window.desktop', 'document.title', 'process.env', 'Buffer.alloc(1)', 'type T = NodeJS.Timeout', 'globalThis.window', 'globalThis["document"]', 'globalThis[name]', '__dirname', 'setImmediate(callback)', 'import(name)'].map(source => ['src/renderer/features/workspace/selection.ts', source]),
    ...['selection', 'useWorkspace'].flatMap(name =>
      [`import '../features/workspace/${name}'`, `export * from '../features/workspace/${name}'`, `import type { Value } from '../features/workspace/${name}'`, `type Value = import('../features/workspace/${name}').Value`, `require('../features/workspace/${name}')`, `import('../features/workspace/${name}')`].map(source => ['src/renderer/app/App.tsx', source])),
    ...['NewSessionDialog', 'useNewSessionLaunch', 'useSessionLaunchController', 'RenameDialog', 'useSessionPresentation'].flatMap(name =>
      [`import '../features/sessions/${name}'`, `export * from '../features/sessions/${name}'`, `import type { Value } from '../features/sessions/${name}'`, `type Value = import('../features/sessions/${name}').Value`, `require('../features/sessions/${name}')`, `import('../features/sessions/${name}')`, `import value = require('../features/sessions/${name}')`].map(source => ['src/renderer/app/App.tsx', source])),
    ...['CommandPalette', 'useCommandPalette'].flatMap(name =>
      [`import '../features/command-palette/${name}'`, `export * from '../features/command-palette/${name}'`, `import type { Value } from '../features/command-palette/${name}'`, `type Value = import('../features/command-palette/${name}').Value`, `require('../features/command-palette/${name}')`, `import('../features/command-palette/${name}')`, `import value = require('../features/command-palette/${name}')`].map(source => ['src/renderer/app/App.tsx', source])),
    ['src/renderer/features/command-palette/CommandPalette.tsx', "import '../workspace/useWorkspace'"],
    ...['node:fs', 'electron', '../../../platform/filesystem/preferences-storage', '../../../modules/conversation/index', '../../../app/main/composition', '../../../app/main/session-mapper'].flatMap(target =>
      [`import '${target}'`, `export * from '${target}'`, `import type { Value } from '${target}'`, `type Value = import('${target}').Value`, `require('${target}')`, `import('${target}')`].map(source => ['src/renderer/features/command-palette/useCommandPalette.ts', source])),
    ...['SettingsDialog', 'useSettingsDraft'].flatMap(name =>
      [`import '../features/preferences/${name}'`, `export * from '../features/preferences/${name}'`, `import type { Value } from '../features/preferences/${name}'`, `type Value = import('../features/preferences/${name}').Value`, `require('../features/preferences/${name}')`, `import('../features/preferences/${name}')`, `import value = require('../features/preferences/${name}')`].map(source => ['src/renderer/app/App.tsx', source])),
    ['src/renderer/features/sessions/NewSessionDialog.tsx', "import '../preferences/useSettingsDraft'"],
    ['src/renderer/features/preferences/SettingsDialog.tsx', "import '../workspace/useWorkspace'"],
    ...['node:fs', 'electron', '../../../platform/filesystem/preferences-storage', '../../../modules/preferences/index', '../../../app/main/desktop-preferences', '../../../app/main/session-mapper'].flatMap(target =>
      [`import '${target}'`, `export * from '${target}'`, `import type { Value } from '${target}'`, `type Value = import('${target}').Value`, `require('${target}')`, `import('${target}')`].map(source => ['src/renderer/features/preferences/useSettingsDraft.ts', source])),
    ['src/renderer/features/workspace/useWorkspace.ts', "import '../sessions/useNewSessionLaunch'"],
    ['src/renderer/features/sessions/NewSessionDialog.tsx', "import '../workspace/useWorkspace'"],
    ...['node:fs', 'electron', '../../../platform/filesystem/project-resources', '../../../modules/sessions/index', '../../../app/main/create-session', '../../../app/main/session-mapper'].flatMap(target =>
      [`import '${target}'`, `export * from '${target}'`, `import type { Value } from '${target}'`, `type Value = import('${target}').Value`, `require('${target}')`, `import('${target}')`].map(source => ['src/renderer/features/sessions/useNewSessionLaunch.ts', source])),
    ['src/renderer/features/workspace/useWorkspace.ts', "import '../../../modules/sessions/index.js'"],
    ...['../features/session-launch', '../features/workspace/RenameDialog', '../features/workspace/useSessionPresentation'].flatMap(target =>
      [`import '${target}'`, `export * from '${target}'`, `import type { Value } from '${target}'`, `type Value = import('${target}').Value`, `require('${target}')`, `import('${target}')`].map(source => ['src/renderer/app/App.tsx', source])),
    ['src/renderer/features/session-launch/index.ts', 'export {}'],
    ['src/renderer/features/workspace/RenameDialog.tsx', 'export {}'],
    ['src/renderer/features/workspace/useSessionPresentation.ts', 'export {}'],
    ['src/renderer/features/workspace/WorkspaceNavigation.tsx', 'export {}'],
    ['src/renderer/modules/ProjectNav.tsx', 'export {}'],
    ['src/renderer/modules/SessionTabs.tsx', 'export {}'],
    ...['workspace/ProjectNav', 'workspace/SessionTabs', 'conversation/ChatPane', 'conversation/chat-state', 'terminal/TerminalPane', 'terminal/terminal-keys', 'change-review/GitPanel', 'change-review/diff-lines'].map(target =>
      ['src/renderer/app/App.tsx', `import '../features/${target}'`]),
    ['src/renderer/features/change-review/GitPanel.tsx', "import { referencePaths } from '../workspace/reference-paths'"],
    ['src/renderer/App.tsx', 'export {}'],
    ['src/renderer/main.tsx', "import './App'"],
    ...['WorkspaceNavigation', 'ChatPane', 'chat-state', 'missing-assistant-diagnostics', 'TerminalPane', 'terminal-keys', 'GitPanel', 'diff-lines'].flatMap(target => [
      [`src/renderer/${target}${/^[A-Z]/.test(target) ? '.tsx' : '.ts'}`, 'export {}'],
      ['src/renderer/app/App.tsx', `import '../${target}'`],
    ]),
    ...['Icon.tsx', 'Modal.tsx', 'theme.ts'].flatMap(target => [
      [`src/renderer/${target}`, 'export {}'],
      ['src/renderer/app/App.tsx', `import '../${target.replace(/\.[^.]+$/, '')}'`],
    ]),
    // Platform/application boundary probes below are synthetic forbidden imports, not callers.
    ...['src/app/main/create-session.ts', 'src/app/main/chat-attachments.ts'].flatMap(file =>
      ['../../platform/electron/utility/session-process-adapter.js', '../../platform/filesystem/session-preparation.js'].flatMap(target =>
        [`import '${target}'`, `export * from '${target}'`, `import type { Value } from '${target}'`, `type Value = import('${target}').Value`, `require('${target}')`, `import('${target}')`].map(source => [file, source]))),
    ...['src/app/main/create-session.ts', 'src/app/main/chat-attachments.ts'].map(file => [file, 'import(name); require(name)']),
    ['src/app/main/other.ts', "import { SessionProcessAdapter } from '../../platform/electron/utility/session-process-adapter.js'"],
    ...['project-resources', 'session-preparation'].flatMap(name =>
      ['../../app/main/composition.js', '../../app/main/session-mapper.js', '../../renderer/app/App.js', '../../modules/sessions/index.js', '../pi/runtime/discovery.js', '../electron/ipc/registrar.js', 'electron', 'react'].flatMap(target =>
        [`import '${target}'`, `export * from '${target}'`, `import type { Value } from '${target}'`, `type Value = import('${target}').Value`, `require('${target}')`, `import('${target}')`].map(source => [`src/platform/filesystem/${name}.ts`, source]))),
    ...['project-resources', 'session-preparation'].flatMap(name => [
      [`src/platform/filesystem/${name}.ts`, 'import(name); require(name)'],
      ['src/renderer/app/App.tsx', `import '../../platform/filesystem/${name}.js'`],
      ['src/shared/ipc/desktop-api.ts', `import '../../platform/filesystem/${name}.js'`],
      ['src/modules/sessions/application/session-coordinator.ts', `import '../../../platform/filesystem/${name}.js'`],
    ]),
    ['src/platform/filesystem/session-preparation.ts', "import type { SessionInfo } from '../../shared/ipc/desktop-api.js'"],
    ...['src/platform/pi/runtime/discovery.ts', 'src/platform/pi/process/environment.ts'].flatMap(file =>
      ['../../../app/main/desktop-preferences.js', '../../filesystem/session-preparation.js', '../../../renderer/app/App.js', '../../../shared/ipc/desktop-api.js', '../../../modules/preferences/index.js', '../../electron/ipc/registrar.js', 'electron', 'node-pty', 'node:child_process', 'child_process', 'node:worker_threads'].flatMap(target => [
        [file, `import '${target}'`], [file, `export * from '${target}'`], [file, `import type { Value } from '${target}'`], [file, `type Value = import('${target}').Value`], [file, `require('${target}')`], [file, `import('${target}')`],
      ])),
    ...['../pi/runtime/discovery.js', '../pi/process/environment.js', '../../app/main/desktop-preferences.js', './session-preparation.js', '../../renderer/app/App.js', 'electron'].flatMap(target =>
      [`import '${target}'`, `export * from '${target}'`, `import type { Value } from '${target}'`, `type Value = import('${target}').Value`, `require('${target}')`, `import('${target}')`].map(source => ['src/platform/filesystem/expand-home.ts', source])),
    ...['pi/runtime/discovery.js', 'pi/process/environment.js', 'filesystem/expand-home.js'].flatMap(target => [
      ['src/renderer/app/App.tsx', `import '../../platform/${target}'`],
      ['src/shared/ipc/desktop-api.ts', `import '../../platform/${target}'`],
    ]),
    ['src/platform/pi/runtime/discovery.ts', 'import(name); require(name)'],
    ['src/platform/filesystem/expand-home.ts', 'import(name)'],
    ...['node:fs/promises', 'electron', 'react', '@mariozechner/pi-ai', '../../../shared/ipc/schemas.js', '../../../platform/pi/runtime/discovery.js', '../../../app/main/bootstrap.js', '../../../platform/filesystem/preferences-storage.js'].flatMap(target => [
      ['src/modules/preferences/application/preferences-application.ts', `import '${target}'`],
      ['src/modules/preferences/application/preferences-application.ts', `export * from '${target}'`],
      ['src/modules/preferences/application/preferences-application.ts', `import type { Value } from '${target}'`],
      ['src/modules/preferences/application/preferences-application.ts', `type Value = import('${target}').Value`],
      ['src/modules/preferences/application/preferences-application.ts', `require('${target}')`],
      ['src/modules/preferences/application/preferences-application.ts', `import('${target}')`],
    ]),
    ['src/modules/preferences/ports.ts', "export * from './application/preferences-application.js'"],
    ['src/modules/preferences/index.ts', "export * from '../../shared/ipc/desktop-api.js'"],
    ['src/modules/preferences/application/preferences-application.ts', "const lazy = import(name); require(name); globalThis['process'].env; Buffer.alloc(1); const timer: NodeJS.Timeout = process.timer"],
    ['src/platform/filesystem/preferences-storage.ts', "import type { PreferenceValues } from '../../modules/preferences/ports.js'"],
    ...['../../app/main/bootstrap.js', '../pi/runtime/discovery.js', '../../renderer/app/App.js', '../electron/ipc/registrar.js', 'electron', 'react'].map(target => ['src/platform/filesystem/preferences-storage.ts', `import '${target}'`]),
    ...['src/renderer/bad.ts', 'src/shared/bad.ts'].map(file => [file, "import { PreferencesApplication } from '../modules/preferences/index.js'"]),
    ['src/modules/change-review/domain/review.ts', "import type { GitStatus } from '../../../shared/ipc/change-review.js'"],
    ['src/modules/change-review/domain/review.ts', "import { lstat } from 'node:fs/promises'"],
    ['src/modules/change-review/application/change-review.ts', "import { GitReviewAdapter } from '../../../platform/git/review-adapter.js'"],
    ['src/modules/change-review/application/change-review.ts', "import type { Pi } from '@mariozechner/pi-ai'"],
    ['src/modules/change-review/ports.ts', "const lazy = import(name); Buffer.alloc(1); process.env"],
    ['src/platform/electron/ipc/change-review-mapper.ts', "import type { ReviewFile } from '../../../modules/change-review/domain/review.js'"],
    ...['../../shared/ipc/change-review.js', '../../app/main/bootstrap.js', '../../renderer/app/App.js', 'electron'].map(target => ['src/platform/git/review-adapter.ts', `import '${target}'`]),
    ...['app/main/bootstrap.js', 'app/main/lifecycle.js', 'app/main/create-window.js', 'app/main/menu.js', 'platform/electron/ipc/register-desktop-ipc.js', 'platform/electron/ipc/registrar.js'].flatMap(target =>
      [['src/renderer/app/App.tsx', `../../${target}`], ['src/shared/ipc/desktop-api.ts', `../../${target}`]].flatMap(([file, specifier]) => [
        [file, `import { value } from '${specifier}'`], [file, `export * from '${specifier}'`],
        [file, `import type { Value } from '${specifier}'`], [file, `type Value = import('${specifier}').Value`],
        [file, `require('${specifier}')`], [file, `import('${specifier}')`],
      ])),
    ...['src/app/main/bootstrap.ts', 'src/platform/electron/ipc/register-desktop-ipc.ts', 'src/platform/electron/ipc/registrar.ts'].flatMap(file => {
      const target = file.startsWith('src/app/') ? '../../renderer/session-state.js' : '../../../renderer/session-state.js';
      return [[file, `import '${target}'`], [file, `export * from '${target}'`], [file, `import type { Value } from '${target}'`], [file, `require('${target}')`], [file, `import('${target}')`], [file, "const channel = 'desktop:bootstrap'"]];
    }),
    ['src/renderer/bad.ts', "import { value } from '../app/main/composition.js'"],
    ['src/renderer/bad.ts', "export * from '../app/main/composition.js'"],
    ['src/renderer/bad.ts', "import type { Value } from '../app/main/composition.js'"],
    ['src/renderer/bad.ts', "type Value = import('../app/main/composition.js').Value"],
    ['src/renderer/bad.ts', "const value = require('../app/main/composition.js')"],
    ['src/renderer/bad.ts', "const value = import('../app/main/composition.js')"],
    ['src/shared/bad.ts', "import { value } from '../app/main/composition.js'"],
    ['src/shared/bad.ts', "export * from '../app/main/composition.js'"],
    ['src/shared/bad.ts', "import type { Value } from '../app/main/composition.js'"],
    ['src/shared/bad.ts', "type Value = import('../app/main/composition.js').Value"],
    ['src/shared/bad.ts', "const value = require('../app/main/composition.js')"],
    ['src/shared/bad.ts', "const value = import('../app/main/composition.js')"],
    ['src/app/main/bad.ts', "import { value } from '../../renderer/session-state.js'"],
    ['src/app/main/bad.ts', "export * from '../../renderer/session-state.js'"],
    ['src/app/main/bad.ts', "import type { Value } from '../../renderer/session-state.js'"],
    ['src/app/main/bad.ts', "type Value = import('../../renderer/session-state.js').Value"],
    ['src/app/main/bad.ts', "const value = require('../../renderer/session-state.js')"],
    ['src/app/main/bad.ts', "const value = import('../../renderer/session-state.js')"],
    ['src/app/main/bad.ts', "const channel = 'desktop:bootstrap'"],
    ['src/app/main/bootstrap.ts', "import { SessionCoordinator } from '../../modules/sessions/application/session-coordinator.js'"],
    ['src/platform/electron/ipc/register-desktop-ipc.ts', "import { ConversationApplication } from '../../../modules/conversation/application/conversation-application.js'"],
    ['src/shared/ipc/worker-protocol.ts', "import type { UtilityProcess } from 'electron'"],
    ['src/shared/ipc/worker-protocol.ts', "import type { RuntimeSend } from '../../modules/conversation/index.js'"],
    ['src/shared/ipc/worker-schemas.ts', "import { spawn } from 'node:child_process'"],
    ['src/shared/ipc/worker-schemas.ts', "import type { ReactNode } from 'react'"],
    ['src/shared/ipc/worker-protocol.ts', "import type { Terminal } from '../../modules/terminal/index.js'"],
    ...['contracts', 'chat', 'chat-validation', 'git', 'missing-assistant-diagnostics'].flatMap(name => [
      [`src/shared/${name}.ts`, 'export {}'],
      ['src/renderer/bad.ts', `import '../shared/${name}'`],
      ['src/shared/ipc/bad.ts', `export * from '../${name}.js'`],
    ]),
    ['src/app/workers/helper.ts', "import '../../platform/pi/rpc/jsonl.js'"],
    ['src/modules/conversation/application/conversation-stream-application.ts', "import { spawn } from 'node:child_process'"],
    ['src/modules/conversation/application/conversation-stream-application.ts', "import { utilityProcess } from 'electron'"],
    ['src/modules/conversation/application/conversation-stream-application.ts', "import { gsap } from 'gsap'"],
    ['src/modules/conversation/application/conversation-stream-application.ts', "import type { Message } from '@mariozechner/pi-ai'"],
    ['src/modules/conversation/application/conversation-stream-application.ts', "type DTO = import('../../../shared/ipc/conversation.js').ToolActivity"],
    ['src/modules/conversation/application/conversation-stream-application.ts', "export * from './conversation-runtime-application.js'"],
    ['src/modules/conversation/domain/stream.ts', "import type { ChatMessage } from '../../../shared/ipc/conversation.js'"],
    ['src/modules/conversation/domain/stream.ts', "const lazy = import(name); globalThis['process'].env"],
    ['src/modules/conversation/domain/stream.ts', "import React from 'react'; const timer: NodeJS.Timeout = process.timer"],
    ['src/platform/pi/rpc/conversation-stream-mapper.ts', "import type { ConversationMessage } from '../../../modules/conversation/domain/stream.js'"],
    ['src/modules/conversation/application/conversation-runtime-application.ts', "import { spawn } from 'node:child_process'"],
    ['src/modules/conversation/application/conversation-runtime-application.ts', "import { utilityProcess } from 'electron'"],
    ['src/modules/conversation/application/conversation-runtime-application.ts', "import type { RpcEvent } from '@mariozechner/pi-coding-agent'"],
    ['src/modules/conversation/domain/runtime.ts', "import type { ChatRuntimeState } from '../../../shared/ipc/conversation.js'"],
    ['src/modules/conversation/domain/runtime.ts', "import type { SessionEvent } from '../../../shared/ipc/events.js'"],
    ['src/modules/conversation/application/conversation-runtime-application.ts', "import React from 'react'"],
    ['src/modules/conversation/application/bad.ts', "import { Agent } from '@mariozechner/pi-coding-agent'"],
    ['src/modules/conversation/application/bad.ts', "import { Adapter } from '../infrastructure/pi-adapter.js'"],
    ['src/modules/conversation/domain/bad.ts', "export * from '../ports.js'"],
    ['src/modules/conversation/ports.ts', "export * from './application/conversation-application.js'"],
    ['src/modules/conversation/index.ts', "export * from '../../app/workers/pi-rpc.worker.js'"],
    ['src/modules/conversation/application/bad.ts', "const fs = require(dynamicPath)"],
    ['src/renderer/bad.ts', "import { ConversationApplication } from '../modules/conversation/index.js'"],
    ['src/shared/bad.ts', "export * from '../modules/conversation/index.js'"],
    ['src/modules/conversation/domain/bad.ts', "import type { SessionInfo } from '../../../shared/ipc/desktop-api.js'"],
    ['src/modules/conversation/domain/bad.ts', "export * from '../../../platform/pi/runtime/discovery.js'"],
    ['src/modules/conversation/domain/bad.ts', "const id = import('node:crypto')"],
    ['src/modules/conversation/domain/bad.ts', "import fs = require('node:fs')"],
    ['src/modules/conversation/domain/bad.ts', "const React = require('react')"],
    ['src/modules/conversation/domain/bad.ts', 'const lazy = import(variable)'],
    ['src/modules/conversation/domain/bad.ts', 'globalThis.process.env; globalThis["Buffer"].alloc(1)'],
    ['src/modules/conversation/domain/bad.ts', 'type Timer = NodeJS.Timeout; const env = process.env; Buffer.alloc(1)'],
    ['src/modules/conversation/domain/bad.ts', "export * from '../application/conversation-application.js'"],
    ['src/modules/conversation/ports.ts', "import type { UtilityProcess } from 'electron'"],
    ['src/modules/conversation/application/bad.ts', "import runtime from '../../../platform/pi/runtime/discovery.js'"],
    ['src/modules/conversation/application/bad.ts', "type DTO = import('../../../shared/ipc/desktop-api.js').SessionInfo"],
    ['src/app/main/bad.ts', "export * from '../../modules/conversation/application/conversation-application.js'"],
    ['src/modules/other/application/bad.ts', "export * from '../../conversation/domain/conversation.js'"],
    ['src/renderer/bad.ts', "import { SessionCoordinator } from '../modules/sessions/index.js'"],
    ['src/shared/bad.ts', "export * from '../modules/sessions/index.js'"],
    ['src/modules/sessions/domain/bad.ts', "import type { SessionInfo } from '../../../shared/ipc/desktop-api.js'"],
    ['src/modules/sessions/domain/bad.ts', "export * from '../../../platform/pi/runtime/discovery.js'"],
    ['src/modules/sessions/domain/bad.ts', "const id = import('node:crypto')"],
    ['src/modules/sessions/domain/bad.ts', "import fs = require('node:fs')"],
    ['src/modules/sessions/domain/bad.ts', "const React = require('react')"],
    ['src/modules/sessions/domain/bad.ts', 'const lazy = import(variable)'],
    ['src/modules/sessions/domain/bad.ts', 'globalThis.process.env; globalThis["Buffer"].alloc(1)'],
    ['src/modules/sessions/domain/bad.ts', 'type Timer = NodeJS.Timeout; const env = process.env; Buffer.alloc(1)'],
    ['src/modules/sessions/domain/bad.ts', "export * from '../application/session-coordinator.js'"],
    ['src/modules/sessions/ports.ts', "import type { UtilityProcess } from 'electron'"],
    ['src/modules/sessions/application/bad.ts', "import runtime from '../../../platform/pi/runtime/discovery.js'"],
    ['src/modules/sessions/application/bad.ts', "type DTO = import('../../../shared/ipc/desktop-api.js').SessionInfo"],
    ['src/app/main/bad.ts', "export * from '../../modules/sessions/application/session-coordinator.js'"],
    ['src/modules/other/application/bad.ts', "export * from '../../sessions/domain/session-ownership.js'"],
    ['src/shared/ipc/bad.ts', "import type { BrowserWindow } from 'electron'"],
    ['src/shared/ipc/bad.ts', "export { readFile } from 'node:fs/promises'"],
    ['src/shared/bad.ts', "type R = import('react').ReactNode"],
    ['src/shared/ipc/bad.ts', "import React from 'react/jsx-runtime'"],
    ['src/shared/ipc/bad.ts', "export * from '../../platform/pi/runtime/discovery.js'"],
    ['src/renderer/bad.ts', "import fs from 'fs'"],
    ['src/renderer/bad.ts', "import pty from 'node-pty'"],
    ['src/renderer/bad.ts', "import runtime from '../platform/pi/runtime/discovery.js'"],
    ['src/renderer/bad.ts', "const worker = import('../app/workers/pty.worker.js')"],
    ['src/renderer/bad.ts', "import electron = require('electron')"],
    ['src/renderer/bad.ts', "const fs = require('node:fs')"],
    ['src/renderer/bad.ts', 'const lazy = import(variable)'],
    ['src/app/main/bad.ts', "const channel = 'desktop:bootstrap'"],
    ['src/app/preload/desktop-api.cts', 'const channel = `desktop:event`'],
    ['src/renderer/bad.ts', "import data from '../../tests/component-preview/fixtures'"],
    ['src/app/main/bad.ts', "export * from '../../../tests/fixtures/fake'"],
  ])('rejects %s: %s', (file, source) => {
    expect(checkSource(file, source, root).length).toBeGreaterThan(0);
  });
  it.each([
    ['src/platform/pi/runtime/discovery.ts', "import { accessSync } from 'node:fs'; import { expandHome } from '../../filesystem/expand-home.js'"],
    ['src/platform/pi/process/environment.ts', "import { searchDirectories, type ResolvedRuntime } from '../runtime/discovery.js'; import path from 'node:path'"],
    ['src/platform/filesystem/expand-home.ts', "import os from 'node:os'; import path from 'node:path'"],
    ['src/platform/filesystem/project-resources.ts', "import { access } from 'node:fs/promises'; import { expandHome } from './expand-home.js'; import type { ProjectResourceInfo } from '../../shared/ipc/desktop-api.js'"],
    ['src/platform/filesystem/session-preparation.ts', "import { stat } from 'node:fs/promises'; import path from 'node:path'; import { expandHome } from './expand-home.js'"],
    ['src/app/main/bootstrap.ts', "import { inspectProjectResources } from '../../platform/filesystem/project-resources.js'"],
    ['src/app/main/composition.ts', "import { prepareProject } from '../../platform/filesystem/session-preparation.js'"],
    ['src/platform/electron/ipc/register-desktop-ipc.ts', "import type { inspectProjectResources } from '../../filesystem/project-resources.js'"],
    ['src/app/main/desktop-preferences.ts', "import type { resolveRuntime } from '../../platform/pi/runtime/discovery.js'"],
    ['src/modules/preferences/ports.ts', "interface PreferenceValues { args: string[]; theme?: 'system' | 'light' | 'dark' }"],
    ['src/modules/preferences/application/preferences-application.ts', "import type { PreferenceValues, PreferencesPersistencePort } from '../ports.js'"],
    ['src/modules/preferences/index.ts', "export { PreferencesApplication } from './application/preferences-application.js'; export type { PreferenceValues } from './ports.js'"],
    ['src/platform/filesystem/preferences-storage.ts', "import { readFile } from 'node:fs/promises'; import { validatePreferences } from '../../shared/ipc/schemas.js'; import type { PreferencesPersistencePort } from '../../modules/preferences/index.js'"],
    ['src/app/main/desktop-preferences.ts', "import type { PreferencesApplication } from '../../modules/preferences/index.js'"],
    ['src/platform/electron/ipc/register-desktop-ipc.ts', "import type { WindowContext } from '../../../app/main/create-window.js'; import { invokeChannels } from '../../../shared/ipc/channels.js'"],
    ['src/app/main/bootstrap.ts', "import { registerDesktopIPC } from '../../platform/electron/ipc/register-desktop-ipc.js'"],
    ['src/app/main/composition.ts', "import { SessionCoordinator } from '../../modules/sessions/index.js'; import { SessionProcessAdapter } from '../../platform/electron/utility/session-process-adapter.js'"],
    ['src/modules/conversation/application/conversation-stream-application.ts', "import { completedTool } from '../domain/stream.js'; import type { StreamSchedulePort } from '../ports.js'"],
    ['src/modules/conversation/domain/stream.ts', "interface ConversationObject { readonly [key: string]: null | string }; const label = 'Pi/NodeJS is adapter-only'"],
    ['src/platform/pi/rpc/conversation-stream-mapper.ts', "import type { ConversationStreamInput } from '../../../modules/conversation/index.js'"],
    ['src/app/main/good.ts', "import { SessionCoordinator } from '../../modules/sessions/index.js'"],
    ['src/modules/sessions/application/good.ts', "import { SessionOwnershipPolicy } from '../domain/session-ownership.js'; import type { SessionProcessPort } from '../ports.js'"],
    ['src/modules/sessions/domain/good.ts', '// process.env; Buffer; import fs from "node:fs";\nconst label = "NodeJS.Timeout"'],
    ['src/renderer/good.ts', "import React from 'react'; import type { DesktopAPI } from '../shared/ipc/desktop-api'"],
    ['src/shared/ipc/good.ts', "export type { SessionEvent } from './conversation.js'"],
    ['src/platform/electron/ipc/good.ts', "import { ipcMain } from 'electron'; import { invokeChannels } from '../../../shared/ipc/channels.js'"],
    ['src/renderer/good.ts', '// import fs from "node:fs";\nconst label = "import electron from electron";'],
    ['src/app/main/good.ts', "import { ConversationApplication } from '../../modules/conversation/index.js'"],
    ['src/modules/conversation/application/good.ts', "import { ConversationFailure } from '../domain/conversation.js'; import type { ConversationRuntimePort } from '../ports.js'"],
    ['src/modules/conversation/domain/good.ts', '// process.env; Buffer; Pi RPC;\nconst label = "node:fs"'],
    ['src/modules/conversation/ports.ts', "import type { RuntimeSend } from './domain/conversation.js'"],
    ['src/platform/git/review-adapter.ts', "import type { ReviewFile } from '../../modules/change-review/index.js'; import { execFile } from 'node:child_process'"],
    ['src/modules/change-review/application/change-review.ts', "import { authorizePreview } from '../domain/review.js'; import type { ReviewRepositoryPort } from '../ports.js'"],
    ['src/renderer/features/workspace/selection.ts', '// window.desktop; process.env; import React from "react";\ninterface WorkspaceSession { id: string; cwd: string }; const label = "document"'],
    ['src/renderer/features/workspace/useWorkspace.ts', "import { useState } from 'react'; import type { DesktopAPI } from '../../../shared/ipc/desktop-api'; import { selectSession } from './selection'"],
    ['src/renderer/features/workspace/index.ts', "export { useWorkspace } from './useWorkspace'; export { selectSession } from './selection'"],
    ['src/renderer/app/App.tsx', "import { CommandPalette, useCommandPalette } from '../features/command-palette'"],
    ['src/renderer/features/command-palette/index.ts', "export { CommandPalette } from './CommandPalette'; export { useCommandPalette } from './useCommandPalette'"],
    ['src/renderer/features/command-palette/CommandPalette.tsx', "import { Dialog } from '../../ui'; import type { useCommandPalette } from './useCommandPalette'"],
    ['src/renderer/features/command-palette/useCommandPalette.ts', "import { useCallback, useState } from 'react'; import type { ChatCommand } from '../../../shared/ipc/conversation'"],
    ['src/renderer/app/App.tsx', "import { SettingsDialog } from '../features/preferences'"],
    ['src/renderer/features/preferences/index.ts', "export { SettingsDialog } from './SettingsDialog'"],
    ['src/renderer/features/preferences/SettingsDialog.tsx', "import { Dialog } from '../../ui'; import { useSettingsDraft } from './useSettingsDraft'"],
    ['src/renderer/features/preferences/useSettingsDraft.ts', "import { useState } from 'react'; import type { Bootstrap, Preferences } from '../../../shared/ipc/desktop-api'"],
    ['src/renderer/features/sessions/NewSessionDialog.tsx', "import { SettingsDialog } from '../preferences'"],
    ['src/renderer/app/App.tsx', "import { NewSessionDialog, RenameDialog } from '../features/sessions'"],
    ['src/renderer/features/sessions/index.ts', "export { NewSessionDialog } from './NewSessionDialog'; export { RenameDialog } from './RenameDialog'"],
    ['src/renderer/features/sessions/NewSessionDialog.tsx', "import { Dialog } from '../../ui'; import { useNewSessionLaunch } from './useNewSessionLaunch'"],
    ['src/renderer/features/sessions/useNewSessionLaunch.ts', "import { useState } from 'react'; import type { ProjectTrust } from '../../../shared/ipc/conversation'"],
    ['src/renderer/features/sessions/NewSessionDialog.tsx', "import { useWorkspace } from '../workspace'"],
    ['src/renderer/features/workspace/useWorkspace.ts', "import { useNewSessionLaunch } from '../sessions'"],
    ['src/renderer/app/App.tsx', "import { ProjectNavigation } from '../features/workspace'; import { ChatPane } from '../features/conversation'; import { TerminalPane } from '../features/terminal'; import { GitPanel } from '../features/change-review'"],
    ['src/renderer/features/workspace/ProjectNav.tsx', "import { groupProjects } from './selection'; import { Icon } from '../../ui'"],
    ['src/renderer/features/workspace/SessionTabs.tsx', "import { InlineRename } from '../../ui'"],
    ['src/renderer/features/workspace/useSessionInput.ts', "import type { TerminalHandle } from '../terminal'; import { referencePaths } from './reference-paths'"],
    ['src/renderer/features/change-review/GitPanel.tsx', "import { referencePaths } from '../workspace'; import { parseDiffLines } from './diff-lines'"],
    ['src/renderer/features/conversation/ChatPane.tsx', "import { reduceChatEvent } from './chat-state'; import { MarkdownView } from '../../ContentView'"],
  ])('allows %s: %s without grep false positives', (file, source) => {
    expect(checkSource(path.join(root, file), source, root)).toEqual([]);
  });
});

it.each([
  'window.desktop.bootstrap()', "window['desktop'].bootstrap()", 'window[key].bootstrap()',
  'const { desktop: renamed } = window; renamed.bootstrap()',
  "const { ['desktop']: renamed } = window", 'const { [key]: renamed } = window',
  'const w = window; w.desktop.bootstrap()', "const w = globalThis.window; w['desktop'].bootstrap()",
  'const w = window; w[key].bootstrap()', 'let w; w = window; w[key].bootstrap()',
  '({ desktop: renamed } = window)', "({ ['desktop']: renamed } = window)", '({ [key]: renamed } = window)',
  '(window as Window).desktop.bootstrap()', 'globalThis.window.desktop.bootstrap()',
])('rejects production raw Desktop access (AST): %s', text => {
  expect(checkSource('src/renderer/features/conversation/ChatPane.tsx', text, process.cwd()).join('\n')).toMatch(/Desktop/);
});
it('allows only the named production client global seam; test/preview assembly is non-production', () => {
  expect(checkSource('src/renderer/app/desktop-client.ts', 'window.desktop', process.cwd())).toEqual([]);
  expect(checkSource('tests/desktop-bridge-fake.ts', 'window.desktop = fake', process.cwd())).toEqual([]);
  expect(checkSource('src/renderer/features/other/desktop-client.ts', 'window.desktop', process.cwd()).join('\n')).toMatch(/Desktop/);
});
