import { useEffect, useRef, useState } from 'react';
import type { Bootstrap, Preferences, SessionInfo } from '../shared/contracts';
import type { ChatCommand, ProjectTrust, SessionKind } from '../shared/chat';
import { TerminalPane, type TerminalHandle } from './TerminalPane';
import { referencePaths } from './terminal-keys';
import { ChatPane } from './ChatPane';
import { GitPanel } from './GitPanel';
import { removeSession, type SessionWorkspace } from './session-state';

const terminalCommands = [
  { name: 'model', label: '选择模型', description: '使用 Pi 原生模型选择器' }, { name: 'thinking', label: '思考强度', description: '选择推理等级' },
  { name: 'resume', label: '恢复历史', description: '打开 Pi 原生会话选择器' }, { name: 'tree', label: '会话分支', description: '查看会话树' },
  { name: 'settings', label: 'Pi 设置', description: '打开原生设置' }, { name: 'login', label: '登录提供商', description: '由 Pi 处理凭据' },
  { name: 'reload', label: '重新加载资源', description: '重新加载扩展和技能' }, { name: 'compact', label: '压缩上下文', description: '执行上下文压缩' },
  { name: 'hotkeys', label: '所有快捷键', description: '以当前 Pi 配置为准' },
];
const basename = (value: string) => value.split(/[\\/]/).filter(Boolean).at(-1) || value;

export function App() {
  const [boot, setBoot] = useState<Bootstrap | null>(null);
  const [sessionState, setSessionState] = useState<SessionWorkspace>({ sessions: [], activeId: null });
  const { sessions, activeId } = sessionState;
  const setSessions = (update: (current: SessionInfo[]) => SessionInfo[]) => setSessionState(current => ({ ...current, sessions: update(current.sessions) }));
  const setActiveId = (id: string) => setSessionState(current => ({ ...current, activeId: current.sessions.some(session => session.id === id) ? id : current.activeId }));
  const [error, setError] = useState('');
  const [launch, setLaunch] = useState<{ cwd: string; kind: SessionKind; mode: 'new' | 'continue' }> ();
  const [newSession, setNewSession] = useState(false); const [settings, setSettings] = useState(false); const [palette, setPalette] = useState(false); const [query, setQuery] = useState('');
  const [searchOpen, setSearchOpen] = useState(false); const [searchText, setSearchText] = useState(''); const [found, setFound] = useState(true);
  const [drafts, setDrafts] = useState<Record<string, string>>({}); const [sessionFilter, setSessionFilter] = useState(''); const [reviewOpen, setReviewOpen] = useState(false); const [renaming, setRenaming] = useState(false);
  const [chatCommands, setChatCommands] = useState<Record<string, ChatCommand[]>>({});
  const handles = useRef(new Map<string, TerminalHandle>());
  const active = sessions.find(session => session.id === activeId); const draft = activeId ? drafts[activeId] || '' : '';
  const setDraft = (text: string) => { if (activeId) setDrafts(current => ({ ...current, [activeId]: text })); };
  const visibleSessions = sessions.filter(session => `${session.title} ${session.cwd}`.toLowerCase().includes(sessionFilter.toLowerCase()));
  const handle = () => activeId ? handles.current.get(activeId) : undefined;

  useEffect(() => { if (!window.desktop) { setError('请使用 npm run dev 启动桌面应用。'); return; } void window.desktop.bootstrap().then(setBoot).catch(error => setError(String(error))); }, []);
  useEffect(() => window.desktop?.onSessionEvent(event => {
    if (event.type === 'session-info') setSessions(current => current.map(session => session.id === event.id ? { ...session, title: event.title ?? session.title, processStatus: event.processStatus ?? session.processStatus, activity: event.activity ?? session.activity } : session));
    if (event.type === 'chat-state' && event.state.activity) setSessions(current => current.map(session => session.id === event.id ? { ...session, activity: event.state.activity! } : session));
    if (event.type === 'exit') setSessions(current => current.map(session => session.id === event.id ? { ...session, processStatus: 'exited', activity: 'idle', exitCode: event.exitCode } : session));
  }), []);
  useEffect(() => {
    const listener = (event: KeyboardEvent) => { const modifier = boot?.platform === 'darwin' ? event.metaKey : event.ctrlKey; if (modifier && event.shiftKey && event.key.toLowerCase() === 'p') { event.preventDefault(); setPalette(value => !value); } if (modifier && event.shiftKey && event.key.toLowerCase() === 'f' && active?.kind === 'terminal') { event.preventDefault(); setSearchOpen(value => !value); } };
    window.addEventListener('keydown', listener, true); return () => window.removeEventListener('keydown', listener, true);
  }, [boot?.platform, active?.kind]);

  const insert = (text: string) => { if (active?.kind === 'chat') setDraft(draft ? `${draft}\n${text}` : text); else handle()?.paste(text); setPalette(false); setQuery(''); };
  const create = async (cwd: string, kind: SessionKind, startMode: 'new' | 'continue' | 'resume', projectTrust: ProjectTrust) => {
    const session = await window.desktop.createSession({ cwd, kind, startMode, projectTrust, cols: 100, rows: 30 });
    setSessions(current => [...current, session]); setSessionState(current => ({ ...current, activeId: session.id })); setNewSession(false); setLaunch(undefined); setSearchOpen(false);
    void window.desktop.bootstrap().then(setBoot).catch(error => setError(String(error)));
  };
  const close = async (id: string) => { try { if (!await window.desktop.closeSession(id)) return; setSessionState(current => removeSession(current, id)); setDrafts(current => { const next = { ...current }; delete next[id]; return next; }); } catch (error) { setError(String(error)); } };
  const attachTerminal = async () => { try { const paths = await window.desktop.chooseAttachments(); if (paths.length) insert(referencePaths(paths)); } catch (error) { setError(String(error)); } };
  const rename = async (title: string) => { if (!active) return; try { if (active.kind === 'chat') await window.desktop.renameChatSession(active.id, title); setSessions(current => current.map(session => session.id === active.id ? { ...session, title } : session)); setRenaming(false); } catch (error) { setError(String(error)); } };

  const paletteCommands = active?.kind === 'chat' ? (chatCommands[active.id] ?? []).map(command => ({ ...command, label: `/${command.name}` })) : terminalCommands.map(command => ({ ...command, source: 'terminal' as const }));

  return <div className="workspace">
    <aside className="sidebar"><div className="brand"><span className="brand-icon">π</span><div>PUA<small>PI UNIVERSAL APP</small></div><span className="version">0.3</span></div>
      <button className="new-button" onClick={() => setNewSession(true)} disabled={!boot}><span>＋</span> 打开项目<span className="button-hint">原生对话</span></button>
      <div className="section-heading">工作中的会话 <span>{sessions.length.toString().padStart(2, '0')}</span></div>
      {sessions.length > 0 && <input className="session-filter" aria-label="筛选会话" placeholder="搜索会话或项目…" value={sessionFilter} onChange={event => setSessionFilter(event.target.value)} />}
      <nav className="sessions" aria-label="会话">{sessions.length === 0 && <p className="muted empty-list">还没有打开的会话。<br />选择项目后直接开始对话。</p>}{visibleSessions.map(session => <div key={session.id} className={`session-row ${session.id === activeId ? 'selected' : ''}`}><button className="session-select" title={session.cwd} onClick={() => { setActiveId(session.id); setSearchOpen(false); }}><span className={`status-dot ${session.processStatus === 'exited' ? 'exited' : session.activity !== 'idle' ? 'busy' : 'running'}`} /><span className="session-label">{session.title}<small>{session.kind === 'chat' ? `对话 · ${session.processStatus === 'starting' ? '连接中' : session.processStatus === 'exited' ? '已退出' : session.activity === 'idle' ? '就绪' : '处理中'}` : '兼容终端'}{session.processStatus === 'exited' ? ` · ${session.kind === 'terminal' ? '已退出 ' : ''}${session.exitCode}` : ''}</small></span></button><button className="close-session" aria-label={`关闭 ${session.title}`} onClick={() => void close(session.id)}>×</button></div>)}</nav>
      {!!boot?.preferences.recentProjects.length && <><div className="section-heading">最近项目</div><div className="recent-list">{boot.preferences.recentProjects.slice(0, 7).map(project => <button key={project} title={project} onClick={() => { setLaunch({ cwd: project, kind: 'chat', mode: 'continue' }); setNewSession(true); }}><span>⌁</span>{basename(project)}<span className="recent-arrow">↗</span></button>)}</div></>}
      <div className="sidebar-bottom"><div className="connection"><span className={`status-dot ${boot?.runtime ? 'running' : 'exited'}`} /><div>{boot?.runtime ? '使用本机 Pi' : '尚未连接 Pi'}<small title={boot?.runtime?.source}>{boot?.runtime?.source || '在桌面设置中选择安装路径'}</small></div></div><button className="settings-button" onClick={() => setSettings(true)} disabled={!boot}>⚙ <span>桌面设置</span><span>↗</span></button></div>
    </aside>
    <main><header className="topbar"><div className="breadcrumbs">工作空间 <span>/</span> <strong>{active?.title || '开始'}</strong>{active && <em>{active.kind === 'chat' ? '原生对话' : '兼容终端'}</em>}</div><div className="topbar-actions"><span className="native-badge">本机 Pi · {active?.kind === 'terminal' ? 'TUI' : 'RPC'}</span><button onClick={() => { setPalette(true); setQuery(''); }} disabled={!active}>⌘ 命令</button></div></header>
      {error && <div className="error-banner" role="alert"><span>{error}</span><button aria-label="关闭错误提示" onClick={() => setError('')}>×</button></div>}
      {!active && <section className="welcome"><div className="welcome-mark">π<span /></div><div className="eyebrow">NATIVE CHAT. FULL PI.</div><h1>与 Pi 对话。<br /><span>清楚地看到工作过程。</span></h1><p>原生消息、工具活动、代码与变更审查集中在一个工作空间。<br />模型、技能、扩展和工具仍由你本机的 Pi 运行。</p><div className="welcome-actions"><button className="primary" onClick={() => setNewSession(true)} disabled={!boot}>打开一个项目 <span>↗</span></button><button onClick={() => setSettings(true)} disabled={!boot}>配置 Pi 路径</button></div>{boot?.runtimeError && <div className="setup-note">{boot.runtimeError}</div>}<div className="feature-grid"><article><span>01 / 对话优先</span><h3>不是终端搬家</h3><p>流式 Markdown、代码块与工具卡片让输出真正可读。</p></article><article><span>02 / 原生能力</span><h3>继续使用你的 Pi</h3><p>桌面通过 RPC 连接用户安装，保留原有模型与工具。</p></article><article><span>03 / 兼容入口</span><h3>TUI 仍然可用</h3><p>登录、设置和自定义终端组件可显式进入兼容终端。</p></article></div><div className="welcome-footnote">原生对话预览版 · macOS arm64 优先验收 · 终端专属扩展需使用兼容模式</div></section>}
      {active && <div className="session-toolbar"><div title={active.cwd} className="project-path"><span>⌁</span> {active.cwd}</div><div><button onClick={() => setRenaming(true)}>重命名</button><button className={reviewOpen ? 'toolbar-selected' : ''} onClick={() => setReviewOpen(value => !value)}>变更审查</button><button onClick={() => void window.desktop.openProject(active.id).catch(error => setError(String(error)))}>打开目录</button>{active.kind === 'terminal' && <><button onClick={() => setSearchOpen(value => !value)}>搜索</button><button onClick={() => void attachTerminal()}>＋ 文件引用</button></>}</div></div>}
      {active?.kind === 'terminal' && searchOpen && <form className="search-bar" onSubmit={event => { event.preventDefault(); setFound(handle()?.search(searchText) ?? false); }}><input autoFocus aria-label="搜索终端历史" placeholder="搜索当前终端缓冲区…" value={searchText} onChange={event => { setSearchText(event.target.value); setFound(true); }} /><span>{!found && '未找到'}</span><button type="button" onClick={() => setFound(handle()?.search(searchText, true) ?? false)}>↑</button><button type="submit">↓</button><button type="button" onClick={() => { handle()?.clearSearch(); setSearchOpen(false); handle()?.focus(); }}>×</button></form>}
      <div className={`workbench ${!active ? 'hidden' : ''}`}><div className="interaction-column"><div className="session-stage">{sessions.map(session => session.kind === 'terminal' ? <TerminalPane key={session.id} session={session} active={session.id === activeId} fontSize={boot?.preferences.fontSize ?? 14} platform={boot?.platform ?? ''} onReady={(id, value) => { if (value) handles.current.set(id, value); else handles.current.delete(id); }} onExit={(id, code) => setSessions(current => current.map(value => value.id === id ? { ...value, processStatus: 'exited', activity: 'idle', exitCode: code } : value))} onError={setError} /> : <ChatPane key={session.id} session={session} active={session.id === activeId} draft={drafts[session.id] || ''} onDraftChange={text => setDrafts(current => ({ ...current, [session.id]: text }))} onError={setError} onTerminalRecovery={() => { setLaunch({ cwd: session.cwd, kind: 'terminal', mode: 'new' }); setNewSession(true); }} onCommands={commands => setChatCommands(current => current[session.id] === commands ? current : { ...current, [session.id]: commands })} />)}</div></div>{active && reviewOpen && <GitPanel key={active.id} sessionId={active.id} onClose={() => setReviewOpen(false)} onReference={text => { setDraft(draft ? `${draft}\n${text}` : text); if (active.kind === 'terminal') insert(text); }} />}</div>
      <footer><span><i className={`status-dot ${active?.processStatus === 'exited' ? 'exited' : 'running'}`} /> {active ? (active.processStatus === 'exited' ? '会话已退出' : active.processStatus === 'starting' ? '正在连接 Pi…' : active.kind === 'chat' ? 'Pi RPC 已连接' : 'Pi 兼容终端运行中') : '本地优先 · 不代理模型请求'}</span><span>{active?.kind === 'chat' ? 'Enter 发送 · Shift + Enter 换行 · Alt + Enter 排到任务后' : active ? 'TUI 快捷键以 /hotkeys 为准' : '你掌握方向，Pi 负责执行。'}</span></footer>
    </main>
    {newSession && boot && <NewSessionDialog initialPath={launch?.cwd || active?.cwd || boot.preferences.recentProjects[0] || boot.home} initialKind={launch?.kind} initialMode={launch?.mode} hasRuntime={!!boot.runtime} onClose={() => { setNewSession(false); setLaunch(undefined); }} onCreate={create} onSettings={() => { setNewSession(false); setSettings(true); }} />}
    {renaming && active && <RenameDialog title={active.title} persistent={active.kind === 'chat'} onClose={() => setRenaming(false)} onSave={rename} />}
    {settings && boot && <SettingsDialog boot={boot} onClose={() => setSettings(false)} onSave={setBoot} />}
    {palette && active && <Modal title={active.kind === 'chat' ? 'Pi 命令' : '终端命令'} onClose={() => setPalette(false)}><input autoFocus className="full-input" aria-label="搜索命令" placeholder="搜索扩展、提示模板或技能…" value={query} onChange={event => setQuery(event.target.value)} /><p className="muted">{active.kind === 'chat' ? '仅显示 Pi RPC 可调用的扩展命令、提示模板和技能；设置、登录与历史选择请使用兼容终端。' : '选择后只插入到 Pi TUI，不自动执行。'}</p><div className="command-list">{paletteCommands.filter(command => `${command.label}${command.name}${command.description || ''}`.toLowerCase().includes(query.toLowerCase())).map(command => <button key={command.name} onClick={() => insert(`/${command.name}`)}><div>{command.label}<small>{command.description || command.source}</small></div><code>/{command.name}</code></button>)}</div></Modal>}
  </div>;
}

function Modal({ title, onClose, children }: { title: string; onClose(): void; children: React.ReactNode }) { const ref = useRef<HTMLDialogElement>(null); useEffect(() => { ref.current?.showModal(); }, []); return <dialog ref={ref} className="modal" onCancel={event => { event.preventDefault(); onClose(); }}><header><h2>{title}</h2><button aria-label="关闭对话框" onClick={onClose}>×</button></header>{children}</dialog>; }

export function NewSessionDialog({ initialKind = 'chat', initialMode = 'new', initialPath, hasRuntime, onClose, onCreate, onSettings }: { initialKind?: SessionKind; initialMode?: 'new' | 'continue'; initialPath: string; hasRuntime: boolean; onClose(): void; onCreate(cwd: string, kind: SessionKind, mode: 'new' | 'continue' | 'resume', trust: ProjectTrust): Promise<void>; onSettings(): void }) {
  const [cwd, setCwd] = useState(initialPath); const [kind, setKind] = useState<SessionKind>(initialKind); const [mode, setMode] = useState<'new' | 'continue' | 'resume'>(initialMode); const [trust, setTrust] = useState<ProjectTrust>('default'); const [inspection, setInspection] = useState<{ cwd: string; paths: string[]; error?: string }>(); const resources = inspection?.cwd === cwd ? inspection.paths : []; const inspecting = inspection?.cwd !== cwd; const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => {
    let current = true; setTrust('default');
    const timer = setTimeout(() => {
      if (cwd.trim()) void window.desktop.inspectProjectResources(cwd).then(value => { if (current) setInspection({ cwd, paths: value.paths }); }).catch(error => { if (current) setInspection({ cwd, paths: [], error: String(error) }); });
    }, 250);
    return () => { current = false; clearTimeout(timer); };
  }, [cwd]);
  useEffect(() => { if (kind === 'chat' && mode === 'resume') setMode('new'); }, [kind]);
  return <Modal title="打开项目" onClose={onClose}><form onSubmit={event => { event.preventDefault(); if (busy || (kind === 'chat' && (inspecting || inspection?.error))) return; setBusy(true); void onCreate(cwd, kind, mode, trust).catch(error => { setError(String(error)); setBusy(false); }); }}><label>项目文件夹</label><div className="input-row"><input aria-label="项目文件夹" autoFocus value={cwd} onChange={event => setCwd(event.target.value)} required /><button type="button" onClick={() => void window.desktop.chooseDirectory().then(value => { if (value) setCwd(value); }).catch(error => setError(String(error)))}>浏览…</button></div><label>界面</label><div className="mode-options">{([['chat', '原生对话', '默认 · RPC 消息与工具卡片'], ['terminal', '兼容终端', '登录、设置和 TUI 专属扩展']] as const).map(([value, label, hint]) => <label key={value} className={kind === value ? 'chosen' : ''}><input type="radio" name="kind" checked={kind === value} onChange={() => setKind(value)} /><span>{label}<small>{hint}</small></span></label>)}</div><label>启动方式</label><div className="mode-options">{([['new', '新会话', '开启独立会话'], ['continue', '继续最近', '恢复本项目最近会话'], ...(kind === 'terminal' ? [['resume', '选择历史', 'Pi 原生选择器'] as const] : [])] as const).map(([value, label, hint]) => <label key={value} className={mode === value ? 'chosen' : ''}><input type="radio" name="mode" checked={mode === value} onChange={() => setMode(value)} /><span>{label}<small>{hint}</small></span></label>)}</div>{kind === 'chat' && resources.length > 0 && <><label>检测到项目资源</label><div className="trust-options">{([['default', '沿用 Pi 已保存决定 / 全局默认'], ['approve', '本次信任并加载项目资源'], ['decline', '本次不加载项目资源']] as const).map(([value, label]) => <label key={value}><input type="radio" name="trust" checked={trust === value} onChange={() => setTrust(value)} />{label}</label>)}</div><p className="muted">RPC 不会显示 Pi 内置信任提示。PUA 不读取或修改 trust.json；“本次信任/不加载”只向这个进程传递对应参数。</p></>}<p className="muted">兼容终端可在内部切换任意历史，因此必须独占：请先关闭其他会话，等待进程退出后再打开。</p>{kind === 'chat' && inspecting && <p>正在检查项目资源…</p>}{(error || inspection?.error) && <p role="alert" className="form-error">{error || inspection?.error}</p>}<div className="modal-actions">{!hasRuntime ? <button type="button" className="primary" onClick={onSettings}>先配置 Pi</button> : <button type="submit" className="primary" disabled={busy || !cwd.trim() || (kind === 'chat' && (inspecting || !!inspection?.error))}>{busy ? '正在打开…' : kind === 'chat' ? '开始对话 ↗' : '打开兼容终端 ↗'}</button>}</div></form></Modal>;
}
function RenameDialog({ title, persistent, onClose, onSave }: { title: string; persistent: boolean; onClose(): void; onSave(title: string): Promise<void> }) { const [value, setValue] = useState(title); return <Modal title="会话名称" onClose={onClose}><form onSubmit={event => { event.preventDefault(); if (value.trim()) void onSave(value.trim()); }}><input autoFocus className="full-input" aria-label="会话显示名" value={value} onChange={event => setValue(event.target.value)} /><p className="muted">{persistent ? '原生对话会通过 Pi set_session_name 保存名称。' : '兼容终端只修改当前窗口标签；持久名称请在 Pi 中使用 /name。'}</p><div className="modal-actions"><button type="submit" className="primary" disabled={!value.trim()}>保存名称</button></div></form></Modal>; }
function SettingsDialog({ boot, onClose, onSave }: { boot: Bootstrap; onClose(): void; onSave(value: Bootstrap): void }) { const [value, setValue] = useState<Preferences>(boot.preferences); const [args, setArgs] = useState(JSON.stringify(value.args)); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const pick = async (key: 'piPath' | 'nodePath') => { try { const selected = await window.desktop.chooseFile(); if (selected) setValue(current => ({ ...current, [key]: selected })); } catch (error) { setError(String(error)); } }; return <Modal title="桌面设置" onClose={onClose}><form onSubmit={event => { event.preventDefault(); setBusy(true); setError(''); try { const parsed: unknown = JSON.parse(args); if (!Array.isArray(parsed) || !parsed.every(item => typeof item === 'string')) throw new Error('参数必须是 JSON 字符串数组'); void window.desktop.savePreferences({ ...value, args: parsed }).then(result => { onSave(result); if (result.runtimeError) { setError(result.runtimeError); setBusy(false); } else onClose(); }).catch(error => { setError(String(error)); setBusy(false); }); } catch (error) { setError(String(error)); setBusy(false); } }}><p className="muted">这里只管理桌面外壳。模型、凭据、工具和扩展继续由 Pi 配置。聊天模式的 mode/session/trust 参数由打开项目界面控制。</p><label>Pi 可执行文件 / CLI .js 路径</label><div className="input-row"><input aria-label="Pi 路径" value={value.piPath} onChange={event => setValue({ ...value, piPath: event.target.value })} /><button type="button" onClick={() => void pick('piPath')}>选择…</button></div><label>Node.js 可执行文件（可选）</label><div className="input-row"><input aria-label="Node.js 路径" value={value.nodePath} onChange={event => setValue({ ...value, nodePath: event.target.value })} /><button type="button" onClick={() => void pick('nodePath')}>选择…</button></div><label>附加 Pi CLI 参数 · JSON 字符串数组</label><input className="full-input mono" aria-label="Pi CLI 参数" value={args} onChange={event => setArgs(event.target.value)} /><label>终端字号 <output>{value.fontSize}px</output></label><input className="range" aria-label="终端字号" type="range" min="10" max="28" value={value.fontSize} onChange={event => setValue({ ...value, fontSize: Number(event.target.value) })} /><div className="runtime-card"><span>当前检测到的 Pi</span><code>{boot.runtime?.source || '未检测到'}</code><small>路径与参数修改仅影响新会话。</small></div>{error && <p role="alert" className="form-error">{error}</p>}<div className="modal-actions"><button type="button" onClick={onClose}>取消</button><button className="primary" type="submit" disabled={busy}>{busy ? '保存中…' : '保存设置'}</button></div></form></Modal>; }
